### ISSUE TITLE
Warning after vacuum start 

### ISSUE THREAD

**Issue by 67rinat** [AlexxIT/VacuumZones#10]
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:738
First occurred: 13:55:29 (2 occurrences)
Last logged: 13:55:29

Entity vacuum.spalnia (<class 'custom_components.vacuum_zones.vacuum.XiaomiVacuum'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author
```

**Comment by perfect-deform** [comment]
Такая же ошибка.
Просто добавил зону в configuration.yaml
```

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

vacuum_zones:
  entity_id: vacuum.roborock_s8_pro_ultra  # change to your vacuum
  zones:
    Коридор:
      room: 1
    Кухня:
      room: 2
```

Пылесосы появились в HA, но при запуске пылесос просто выкатывается с базы, и возвращается обратно.
