### ISSUE TITLE
Не удается запустить последовательность зон (+вариант решения)

### ISSUE THREAD

**Issue by 0neel** [AlexxIT/VacuumZones#2]
Мой Xiaomi Vacuum Cleaner (первого поколения) не реагирует на команду зональной уборки, если находится в состоянии возврата на базу. Поэтому последовательность зон в этой интеграции не работает.

Я заметил, что сначала нужно поставить пылесос на паузу и только потом посылать следующую команду на зональную уборку, поэтому в качестве временного решения я сконфигурировал интеграцию следующим образом:
```yaml
vacuum_zones:
  entity_id: vacuum.xiaomi_vacuum_cleaner
  zones:
    zone1:
      sequence:
        - service: script.vacuum_pause
      zone: [[...]]
    zone2:
      sequence:
        - service: script.vacuum_pause
      zone: [[...]]

script:
  vacuum_pause:
    sequence:
      - service: vacuum.pause
        target:
          entity_id: vacuum.xiaomi_vacuum_cleaner
```

И это работает! Сначала пылесос начинает возврат на базу, но потом становится на паузу и переходит к следующей зоне.

<details>
<summary>P.S.</summary>

Огромное спасибо за интеграцию, раньше я делал нечто подобное с помощью скрипта запускающего зональную уборку в связке со сценарием на стороне Яндекса для использования более естественных команд в духе "Пропылесось в такой-то зоне".
</details>
