### ISSUE TITLE
repeats when cleaning a room

### ISSUE THREAD

**Issue by G1K** [AlexxIT/VacuumZones#5]
When cleaning a segment, there is no repeat option, although the application does.
The miio service also does not have this parameter, and it’s impossible to add this parameter just like that.

There is a way to use sending a custom command

```
service: vacuum.send_command
target:
  entity_id: vacuum.xiaomi_vacuum
data: 
  command: app_segment_clean
  params:
    - segments:
        - 17
      repeat: 2

```

Or if you [change the component code](https://github.com/AlexxIT/VacuumZones/blob/master/custom_components/vacuum_zones/vacuum.py#L76-L82), for example like this

```

        if 'room' in self.config:
            await self.hass.services.async_call(
                'vacuum', 'send_command', {
                    'entity_id': self.config['entity_id'],
                    'command': 'app_segment_clean',
                    'params':
                        [
                            {
                                'segments': [
                                    self.config['room']
                                ],
                                'repeat': self.config.get('repeats', 1)
                            }
                        ]

                }, blocking=True)
```
