### ISSUE TITLE
Не запускается уборка комнат

### ISSUE THREAD

**Issue by c1tru55** [AlexxIT/VacuumZones#6]
Установил интеграцию, добавил в конфиг:
```
vacuum_zones:
  entity_id: vacuum.roborock_vacuum_s5
  zones:
    Спортзал:
      room: 1
    Кухня:
      room: 2
    Спальня:
      room: 16
    Гостиная:
      room: 17
    Коридор:
      room: 18
    Прихожая:
      room: 19
    Вокруг стола:
      zone:
        - - 26619
          - 29000
          - 29431
          - 30869
        - - 27600
          - 30869
          - 29431
          - 31764
    Диван:
      goto: [29130, 26200]
    Все комнаты кроме кухни:
      sequence:
        - service: persistent_notification.create
          data:
            message: Starting a complete house cleaning
      room: [19, 18, 17, 16, 1]
```
(значения взяты из виджета Xiaomi Vacuum Map Card), но когда говорю Яндекс станции: `Алиса, пропылесось в прихожей` - Алиса отвечает: `Простите, но в этой комнате такого нет`. Что я делаю не так?
